language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nU2qGkrmcUcOZnG959iIDgYovkmD7RaYVJywXLT2yQxwHT+FM4VbtP4ZhkCLS6os3HIx7bxuShI2an6aN4uwyDE4WQv1EtI/gPNltTPHauyS7LaA2P/IpdIxBdrlBa69GIM5uRRHRO+EoYICB+A2ERtzXYEg7+zNlT52cuTzAFN/axZTmIjGokTonNEbJp982/nsP6XkJcBw12GFDPY0+FmW7yTPBB4dEdsXNXYv4lLXjticqSmym1ePk4QI5lLOOJsxEoWu2egJAE8DUT8hCxQ01IzhBVGiXMcdWopxlmDz1N23KI5zX9qwQ63+tredczfiMfB4hgNHY0ZZE2RjSgLB3b6Uk1seIcG9xnzfgbCb3TQuGDSX/eeDsBanr3l+Zf8zDD5myT/VOeXE6aZNZK7m4B8AfQVLOo980p0G9OnIKO4HSM026yDxXXBBmwcMqphX0ZfjdLbxMATTq8GLLV8IueqR1V5uwdi9kF8tZ+Hqx3/PaZbipSJ9C6RxUXYImO98HOGsLjhv6QncTO1p8y1KEdeLm1WP7SFCy8ZZN/sHLTkfNK5YuhaTfZuaxXlea7iDuVvLQrgAJzwEGOD0t0Pot/rT5yjdkU038YqhvUC8I1PF4PounknnL9396dVTrPHMhjoJD9Ql+cMY2IdzNa5rccIrpT3ivqyZNb2XvCk="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - cd src

addons:
  apt:
    packages:
    - gcc-multilib
    - libx11-dev:i386
  coverity_scan:
    project:
      name: "9fans/vx32"
      description: "Build submitted via Travis CI"
    notification_email: 0intro@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master

script:
  - make clean
  - make
